### ISSUE TITLE
escape sign in page

### ISSUE THREAD

**Issue by kevinlewis13** [kevinlewis13/harrys-chicken#92]
currently there is no way to escape the sign in without directing browser explicity to new url

**Comment by andyjac** [comment]
I think I know why this is occurring. The back button is technically working, but since we are rerouting them from `/admin` to `/admin/sign_in` when they are not signed in, pushing the back button on the sign in page is sending them to `/admin`, which reroutes them back to sign in. The fix here is to always take them to the sign in page first, where we check to see if they are signed in and if they are we reroute them to the admin page.

**Comment by kevinlewis13** [comment]
I was thinking it was something along those lines. Shouldn't be too hard to
fix.
